/**
 * Données de démonstration — utilisées quand Supabase n'est pas configuré,
 * pour que l'app soit immédiatement explorable et jolie.
 * Les `photo_url` sont nuls : les cartes affichent un dégradé basé sur la
 * couleur dominante (aucune dépendance réseau).
 */

const uid = (n) => `demo-${n.toString().padStart(4, '0')}`

export const DEMO_PROFILE = {
  id: 'demo-user',
  prenom: 'Léa',
  avatar_emoji: '🦋',
  styles_preferes: ['Chic', 'Minimaliste', 'Vintage'],
  couleurs_fetiches: ['#E8C547', '#FF6B6B', '#0D0D0D'],
  budget_moyen: 45,
  points: 185,
  badges: ['first_look', 'fashionista'],
}

export const DEMO_VETEMENTS = [
  {
    id: uid(1),
    nom: 'Chemise en lin beige',
    categorie: 'haut',
    couleur_dominante: 'Beige',
    couleur_hex: '#D9C7A8',
    couleurs_secondaires: ['Blanc cassé'],
    style: ['chic', 'casual'],
    saison: ['printemps', 'été'],
    occasion: ['travail', 'quotidien'],
    marque: 'COS',
    taille: 'M',
    prix_achat: 32,
    tags: ['favori'],
    nb_ports: 14,
    derniere_date_port: '2026-06-30',
  },
  {
    id: uid(2),
    nom: 'Pantalon tailleur noir',
    categorie: 'bas',
    couleur_dominante: 'Noir',
    couleur_hex: '#1A1A1A',
    couleurs_secondaires: [],
    style: ['chic', 'soirée'],
    saison: ['automne', 'hiver', 'printemps'],
    occasion: ['travail', 'soirée'],
    marque: 'Zara',
    taille: '38',
    prix_achat: 40,
    tags: ['favori'],
    nb_ports: 22,
    derniere_date_port: '2026-07-02',
  },
  {
    id: uid(3),
    nom: 'Baskets blanches minimalistes',
    categorie: 'chaussures',
    couleur_dominante: 'Blanc',
    couleur_hex: '#F2F2EF',
    couleurs_secondaires: ['Gris'],
    style: ['casual', 'streetwear'],
    saison: ['printemps', 'été', 'automne'],
    occasion: ['quotidien', 'sport'],
    marque: 'Veja',
    taille: '39',
    prix_achat: 95,
    tags: [],
    nb_ports: 30,
    derniere_date_port: '2026-07-04',
  },
  {
    id: uid(4),
    nom: 'Robe corail fluide',
    categorie: 'robe',
    couleur_dominante: 'Corail',
    couleur_hex: '#FF6B6B',
    couleurs_secondaires: ['Rose'],
    style: ['soirée', 'chic'],
    saison: ['été'],
    occasion: ['soirée', 'cérémonie'],
    marque: 'Sézane',
    taille: 'M',
    prix_achat: 78,
    tags: ['favori', 'stocke'],
    nb_ports: 3,
    derniere_date_port: '2026-05-12',
  },
  {
    id: uid(5),
    nom: 'Veste en jean vintage',
    categorie: 'manteau',
    couleur_dominante: 'Bleu denim',
    couleur_hex: '#4A6C8C',
    couleurs_secondaires: ['Indigo'],
    style: ['vintage', 'casual', 'streetwear'],
    saison: ['printemps', 'automne'],
    occasion: ['quotidien'],
    marque: 'Levi’s',
    taille: 'M',
    prix_achat: 25,
    tags: [],
    nb_ports: 18,
    derniere_date_port: '2026-06-20',
  },
  {
    id: uid(6),
    nom: 'Pull maille moutarde',
    categorie: 'haut',
    couleur_dominante: 'Moutarde',
    couleur_hex: '#E8C547',
    couleurs_secondaires: ['Ocre'],
    style: ['casual', 'chic'],
    saison: ['automne', 'hiver'],
    occasion: ['quotidien', 'travail'],
    marque: 'American Vintage',
    taille: 'S',
    prix_achat: 55,
    tags: ['favori'],
    nb_ports: 9,
    derniere_date_port: '2026-04-02',
  },
  {
    id: uid(7),
    nom: 'Jean brut droit',
    categorie: 'bas',
    couleur_dominante: 'Bleu foncé',
    couleur_hex: '#26364A',
    couleurs_secondaires: [],
    style: ['casual', 'streetwear'],
    saison: ['automne', 'hiver', 'printemps'],
    occasion: ['quotidien'],
    marque: 'Nudie',
    taille: '28',
    prix_achat: 60,
    tags: [],
    nb_ports: 40,
    derniere_date_port: '2026-07-01',
  },
  {
    id: uid(8),
    nom: 'Foulard soie menthe',
    categorie: 'accessoire',
    couleur_dominante: 'Menthe',
    couleur_hex: '#A8E6CF',
    couleurs_secondaires: ['Vert d’eau'],
    style: ['chic', 'vintage'],
    saison: ['printemps', 'été'],
    occasion: ['travail', 'cérémonie'],
    marque: 'Hermès (chiné)',
    taille: 'U',
    prix_achat: 20,
    tags: ['favori'],
    nb_ports: 5,
    derniere_date_port: '2026-03-15',
  },
  {
    id: uid(9),
    nom: 'Bottines cuir cognac',
    categorie: 'chaussures',
    couleur_dominante: 'Cognac',
    couleur_hex: '#8A5A2B',
    couleurs_secondaires: ['Marron'],
    style: ['chic', 'vintage'],
    saison: ['automne', 'hiver'],
    occasion: ['travail', 'soirée'],
    marque: 'Sézane',
    taille: '39',
    prix_achat: 120,
    tags: ['stocke'],
    nb_ports: 2,
    derniere_date_port: '2026-02-01',
  },
  {
    id: uid(10),
    nom: 'T-shirt blanc oversize',
    categorie: 'haut',
    couleur_dominante: 'Blanc',
    couleur_hex: '#F5F5F0',
    couleurs_secondaires: [],
    style: ['casual', 'streetwear', 'minimaliste'],
    saison: ['printemps', 'été'],
    occasion: ['quotidien', 'sport'],
    marque: 'Uniqlo',
    taille: 'M',
    prix_achat: 15,
    tags: [],
    nb_ports: 26,
    derniere_date_port: '2026-07-03',
  },
  {
    id: uid(11),
    nom: 'Short en lin terracotta',
    categorie: 'bas',
    couleur_dominante: 'Terracotta',
    couleur_hex: '#C56B4A',
    couleurs_secondaires: ['Rouille'],
    style: ['casual', 'boho'],
    saison: ['été'],
    occasion: ['quotidien'],
    marque: 'Mango',
    taille: '38',
    prix_achat: 22,
    tags: ['a_donner'],
    nb_ports: 1,
    derniere_date_port: '2025-08-10',
  },
  {
    id: uid(12),
    nom: 'Casquette noire',
    categorie: 'accessoire',
    couleur_dominante: 'Noir',
    couleur_hex: '#111111',
    couleurs_secondaires: [],
    style: ['streetwear', 'sport'],
    saison: ['printemps', 'été', 'automne'],
    occasion: ['quotidien', 'sport'],
    marque: 'Carhartt',
    taille: 'U',
    prix_achat: 28,
    tags: [],
    nb_ports: 12,
    derniere_date_port: '2026-06-28',
  },
]

export const DEMO_HISTORIQUE = [
  { id: 'h1', date_port: '2026-07-04', humeur: '😎 Décontracté', meteo: '24°C ☀️', vetements: [uid(10), uid(7), uid(3)] },
  { id: 'h2', date_port: '2026-07-03', humeur: '💼 Mode Pro', meteo: '22°C ⛅', vetements: [uid(1), uid(2), uid(9)] },
  { id: 'h3', date_port: '2026-07-02', humeur: '🎉 Festif', meteo: '26°C ☀️', vetements: [uid(4), uid(3), uid(8)] },
  { id: 'h4', date_port: '2026-07-01', humeur: '🖤 Dark Mood', meteo: '19°C 🌧️', vetements: [uid(10), uid(7), uid(12)] },
  { id: 'h5', date_port: '2026-06-30', humeur: '🌿 Zen/Nature', meteo: '23°C ⛅', vetements: [uid(1), uid(11), uid(3)] },
]
